name: CircuitAddons
version: '1.2.1'
main: cool.circuit.circuitAddons.CircuitAddons
api-version: '1.21'

commands:
  circuitaddons:
    description: 'A utility plugin for 1.21.4'
    permission: coolcircuit.menu
    aliases: [ca]
  alltitle:
    description: 'Display a title for all players'
    aliases: [at,atitle,allt]
  manage:
    description: 'Manage a player'
  sethome:
    description: 'Sets a home'
  home:
    description: 'Teleports to a home'
  setspawn:
    description: 'Sets the spawn point!'
  spawn:
    description: 'Teleports to the spawn point!'
    permission: circuitaddons.spawn
  balcheck:
    description: 'Checks the player''s balance!'
    permission: circuitaddons.balcheck
  shop:
    description: 'Opens the shop!'
    permission: circuitaddons.shop
  economy:
    aliases: [eco]
    description: 'Economy related stuff.'
    permission: circuitaddons.economy
  banks:
    description: 'Shows all banks.'
    permission: circuitaddons.banks
  mute:
    description: 'Mutes a player'
    permission: circuitaddons.mute
  unmute:
    description: 'Unmutes a player'
    permission: circuitaddons.unmute
  blacklist:
    description: 'Adds words to the blacklist'
    permission: circuitaddons.blacklist
  biome:
    description: 'Shows what biome you are in!'
    permission: circuitaddons.biome
  gma:
    description: 'Sets your gamemode to adventure!'
    permission: circuitaddons.gma
  gmc:
    description: 'Sets your gamemode to creative!'
    permission: circuitaddons.gmc
  gms:
    description: 'Sets your gamemode to survival!'
    permission: circuitaddons.gms
  gmsp:
    description: 'Sets your gamemode to spectator!'
    permission: circuitaddons.gmsp
  slotguesser:
    description: 'A little minigame'
    permission: circuitaddons.slotguesser
  paintdrying:
    description: 'A paint drying simulator'
    permission: circuitaddons.paintdrying
  minecraft:
    description: 'Literal minecraft inside of minecraft!'
    permission: circuitaddons.minecraft
  createentity:
    description: 'Creates an entity!'
    permission: circuitaddons.createentity
  enchanting:
    description: 'Enchanting table!'
    permission: circuitaddons.enchanting
  heal:
    description: 'Heals a player'
    permission: circuitaddons.heal
  nick:
    description: 'Nicks a player'
    permission: circuitaddons.nick
  unnick:
    description: 'Removes a nick name from a player'
    permission: circuitaddons.unnick
  fancychat:
    description: 'Send a fancy chat message!'
    permission: circuitaddons.fancychat
  prefix:
    description: 'Set a players prefix!'
    permission: circuitaddons.prefix
  permissions:
    description: 'Handles groups and permissions!'
    permission: circutiaddons.permissions
  vanish:
    description: 'Vanishes yourself'
    permission: circuitaddons.vanish
  namecolor:
    description: 'Changes the color of your name!'
    permission: circuitaddons.namecolor
  fireball:
    description: 'Gives a player a fireball'
    permission: circuitaddons.fireball
  lootbox:
    description: 'Opens the lootbox manager menu!'
    permission: circuitaddons.lootbox
  lootboxes:
    description: 'Lootbox stuff'
  del:
    description: 'Deletes stuff'
  display:
    description: 'Displays stuff'

depend: [Vault, PlaceholderAPI]
